import { QuestWithViews } from "./types";

export const questData: QuestWithViews[] = [
  // GRID 1: SECRECY + OPPRESSION (9 missions)
  {
    gm: {
      id: "loose-lips-boilerhouse",
      title: "Loose Lips at the Boilerhouse",
      category: "Secrecy",
      hook: "In Lanternward's lower taverns, a Guard relay technician stationed near Bramblecourt's Watchline Outpost has been drinking himself senseless. Underflow scouts report he's begun loudly bragging about the Council's upcoming patrol realignments. If he sobers or someone reports him, the chance is gone. Slip into the Boilerhouse, play the room, and ease secrets out before he remembers his oath.",
      costR: 0,
      success: { S: 5, U: 5 },
      failure: { S: -5 },
      optionalInvestments: [
        {
          label: "Bribes",
          costR: 1,
          effectOnSuccess: { S: 5 },
        },
        {
          label: "Forged Guard union badges",
          costR: 2,
          effectOnSuccess: { S: 5 },
          ruleText: "Reduce risk of detection",
        },
      ],
      complications: [
        "Guard patrols",
        "Suspicious patrons",
        "Engineer sobers up",
        "Watchline Outpost security",
      ],
      ties: [
        "Ember Cell",
        "Haven Cell",
        "City Guard Relay Division",
        "Boilerhouse tavern",
        "Bramblecourt",
      ],
      availabilityOppression: "Low",
      availabilitySecondary: { track: "S", requirement: "Low" },
    },
    player: {
      title: "Loose Lips at the Boilerhouse",
      hook: "In Lanternward's lower taverns, a Guard relay technician stationed near Bramblecourt's Watchline Outpost has been drinking himself senseless. Underflow scouts report he's begun loudly bragging about the Council's upcoming patrol realignments. If he sobers or someone reports him, the chance is gone. Slip into the Boilerhouse, play the room, and ease secrets out before he remembers his oath.",
    },
  },
  {
    gm: {
      id: "listen-to-pipes",
      title: "Listen to the Pipes",
      category: "Secrecy",
      hook: "The Lower Siphonworks produce faint resonance pulses as their pressure regulators cycle. A Plumber's Union whistleblower swears that, for eight seconds every hour, the Arcano-Engine Guild's encrypted Guard transmissions leak raw through the pipe lattice. Your team must reach a maintenance alcove in Bramblecourt, attune a receiver, and capture whatever unfiltered data rides the steam.",
      costR: 0,
      success: { S: 5, H: 5 },
      failure: { S: -5 },
      failureNotes: "Brief alert → –Secrecy",
      optionalInvestments: [
        {
          label: "Resonance dampener",
          costR: 1,
          effectOnSuccess: { S: 5 },
        },
        {
          label: "Harmonic isolator",
          costR: 3,
          effectOnSuccess: { S: 5 },
          ruleText: "Guaranteed clean intercept",
        },
      ],
      complications: [
        "Guard monitoring",
        "Timing critical",
        "Resonance detection",
        "Lower Siphonworks security",
      ],
      ties: [
        "Underflow Cell",
        "Plumber's Union",
        "Arcano-Engine Guild",
        "Bramblecourt",
      ],
      availabilityOppression: "Low",
      availabilitySecondary: { track: "S", requirement: "Med" },
    },
    player: {
      title: "Listen to the Pipes",
      hook: "The Lower Siphonworks produce faint resonance pulses as their pressure regulators cycle. A Plumber's Union whistleblower swears that, for eight seconds every hour, the Arcano-Engine Guild's encrypted Guard transmissions leak raw through the pipe lattice. Your team must reach a maintenance alcove in Bramblecourt, attune a receiver, and capture whatever unfiltered data rides the steam.",
    },
  },
  {
    gm: {
      id: "lantern-drift-signal-run",
      title: "Lantern Drift Signal Run",
      category: "Propaganda",
      hook: "High secrecy gives the People's Sword a rare window to reconnect their fractured teams. Elijah proposes floating coded paper lanterns down the underground stream running from Myco-Falls to the Overflow Vaults. The drifting lights carry silent instructions, whispers of hope, and a promise that the Sword still breathes. If intercepted, the Guard could unravel half the resistance map.",
      costR: 0,
      success: { H: 5 },
      failure: { U: -5 },
      failureNotes: "Signals misread → –Unity",
      optionalInvestments: [
        { label: "Lantern stock", costR: 1, effectOnSuccess: { H: 5 } },
        {
          label: "Waterproof seals",
          costR: 2,
          effectOnSuccess: { H: 5 },
          ruleText: "Reduce risk of message loss",
        },
      ],
      complications: [
        "River currents",
        "Guard patrols",
        "Message interception",
        "Myco-Falls security",
      ],
      ties: ["Haven Cell", "Underflow Cell", "Myco-Falls", "Overflow Vaults"],
      availabilityOppression: "Low",
      availabilitySecondary: { track: "S", requirement: "High" },
    },
    player: {
      title: "Lantern Drift Signal Run",
      hook: "High secrecy gives the People's Sword a rare window to reconnect their fractured teams. Elijah proposes floating coded paper lanterns down the underground stream running from Myco-Falls to the Overflow Vaults. The drifting lights carry silent instructions, whispers of hope, and a promise that the Sword still breathes. If intercepted, the Guard could unravel half the resistance map.",
    },
  },
  {
    gm: {
      id: "soot-glass-heist",
      title: "The Soot-Glass Heist",
      category: "Secrecy",
      hook: "The Guard's Surveillance Bureau is moving crates of fresh soot-glass lenses through Blast Block, destined for high-altitude watchtowers above Council's Reach. If deployed, they can peer through smoke, spores, and darkness — a death sentence for Underflow secrecy. Intercept a single shipment under the industrial cranes before it reaches the loading spire.",
      costR: 0,
      success: { S: 5 },
      failure: { S: -5, O: 1 },
      failureNotes: "–Secrecy, +Oppression",
      optionalInvestments: [
        { label: "Smoke charges", costR: 1, effectOnSuccess: { S: 5 } },
        {
          label: "Crane route map",
          costR: 2,
          effectOnSuccess: { S: 5 },
          ruleText: "Reduce difficulty of infiltration",
        },
      ],
      complications: [
        "Guard warehouse",
        "Surveillance systems",
        "Heavy security",
        "Blast Block industrial cranes",
      ],
      ties: [
        "Ember Cell",
        "Industrial Compliance Board",
        "Arcano-Engine Guild",
        "Blast Block",
        "Council's Reach",
      ],
      availabilityOppression: "Med",
      availabilitySecondary: { track: "S", requirement: "Low" },
    },
    player: {
      title: "The Soot-Glass Heist",
      hook: "The Guard's Surveillance Bureau is moving crates of fresh soot-glass lenses through Blast Block, destined for high-altitude watchtowers above Council's Reach. If deployed, they can peer through smoke, spores, and darkness — a death sentence for Underflow secrecy. Intercept a single shipment under the industrial cranes before it reaches the loading spire.",
    },
  },
  {
    gm: {
      id: "alleyway-relay-disruption",
      title: "Alleyway Relay Disruption",
      category: "Secrecy",
      hook: "Arcano-tech alley relays lace Bramblecourt like veins, feeding Guard surveillance into the Ivory Spire Hub in Council's Reach. Disabling even one throws the algorithmic patrol grid off balance. The relay is hidden between two collapsed laundry towers — guarded only by a bored technician and a motion ward. A surgical operation might keep alarms silent.",
      costR: 0,
      success: { S: 5, O: -1 },
      failure: { S: -5 },
      failureNotes: "Relay logs attackers → –Secrecy",
      optionalInvestments: [
        {
          label: "Shaped charge",
          costR: 2,
          effectOnSuccess: { S: 5 },
        },
        {
          label: "Timed overload kit",
          costR: 3,
          effectOnSuccess: { S: 5 },
          ruleText: "Prevent relay from logging attack",
        },
      ],
      complications: [
        "Guard patrols",
        "Relay security",
        "Detection risk",
        "Ivory Spire Hub",
      ],
      ties: ["Ember Cell", "Underflow Cell", "Bramblecourt", "Council's Reach"],
      availabilityOppression: "Med",
      availabilitySecondary: { track: "S", requirement: "Med" },
    },
    player: {
      title: "Alleyway Relay Disruption",
      hook: "Arcano-tech alley relays lace Bramblecourt like veins, feeding Guard surveillance into the Ivory Spire Hub in Council's Reach. Disabling even one throws the algorithmic patrol grid off balance. The relay is hidden between two collapsed laundry towers — guarded only by a bored technician and a motion ward. A surgical operation might keep alarms silent.",
    },
  },
  {
    gm: {
      id: "ghostlines-above-foundry",
      title: "Ghostlines Above the Foundry",
      category: "Secrecy",
      hook: "From the rusted rooftops of the Ironclad Foundry, one can watch Guard troop movements slither between Lanternward and Bramblecourt. With secrecy high, your team can cross the vent bridges undetected and tap their encrypted pathing beacons. The heat, steam, and metal groans create a natural cover — but a single slip could cascade into a factory lockdown.",
      costR: 0,
      success: { S: 5, U: 5 },
      failure: { S: -5 },
      failureNotes: "Minimal, but –Secrecy on detection",
      optionalInvestments: [
        { label: "Climbing hooks", costR: 1, effectOnSuccess: { S: 5 } },
        {
          label: "Silence wards",
          costR: 3,
          effectOnSuccess: { S: 5 },
          ruleText: "Ignore first failed Stealth roll",
        },
      ],
      complications: [
        "Foundry security",
        "Rooftop patrols",
        "Detection systems",
        "Factory lockdown risk",
      ],
      ties: [
        "Ember Cell",
        "Ironclad Foundry workers",
        "Lanternward",
        "Bramblecourt",
      ],
      availabilityOppression: "Med",
      availabilitySecondary: { track: "S", requirement: "High" },
    },
    player: {
      title: "Ghostlines Above the Foundry",
      hook: "From the rusted rooftops of the Ironclad Foundry, one can watch Guard troop movements slither between Lanternward and Bramblecourt. With secrecy high, your team can cross the vent bridges undetected and tap their encrypted pathing beacons. The heat, steam, and metal groans create a natural cover — but a single slip could cascade into a factory lockdown.",
    },
  },
  {
    gm: {
      id: "break-watchers-eye",
      title: "Break the Watcher's Eye",
      category: "Secrecy",
      hook: "Under crushing Guard presence, Underflow runners have discovered a fully operational Watcher Node in Council's Reach — a central lens controlling surveillance over the Underflow entry points. Destroying it will free tunnel teams for weeks but will trigger immediate reprisals. You'll need to time your charge, breach the node, and escape before the Guard's Aerial Patrol Division rains fire.",
      costR: 0,
      success: { O: -1 },
      failure: { S: -5, O: 1 },
      failureNotes: "–Secrecy, +Oppression",
      optionalInvestments: [
        { label: "Explosives", costR: 2, effectOnSuccess: { O: -1 } },
        {
          label: "Diversion squad",
          costR: 3,
          effectOnSuccess: { O: -1 },
          ruleText: "Reduce Guard response time",
        },
      ],
      complications: [
        "Heavy security",
        "Guard response",
        "Surveillance backup",
        "Aerial Patrol Division",
      ],
      ties: [
        "Ember Cell",
        "Underflow Cell",
        "City Guard Aerial Division",
        "Council's Reach",
      ],
      availabilityOppression: "High",
      availabilitySecondary: { track: "S", requirement: "Low" },
    },
    player: {
      title: "Break the Watcher's Eye",
      hook: "Under crushing Guard presence, Underflow runners have discovered a fully operational Watcher Node in Council's Reach — a central lens controlling surveillance over the Underflow entry points. Destroying it will free tunnel teams for weeks but will trigger immediate reprisals. You'll need to time your charge, breach the node, and escape before the Guard's Aerial Patrol Division rains fire.",
    },
  },
  {
    gm: {
      id: "sleeper-trace-protocol",
      title: "Sleeper Trace Protocol",
      category: "Secrecy",
      hook: "A pattern emerges: coded market receipts, misaligned alley markers, and a sudden shift in Guard foot patrols in Lanternward. Rose believes a sleeper agent has been activated. Your team must follow subtle missteps through Bramblecourt's maze-like backstreets to identify the mole before they pinpoint the Sword's safehouses.",
      costR: 0,
      success: { U: 5, S: 5 },
      failure: { O: 1 },
      failureNotes: "Sleeper reports → +Oppression",
      optionalInvestments: [
        { label: "Disguise kit", costR: 1, effectOnSuccess: { S: 5 } },
        {
          label: "Message interceptor",
          costR: 2,
          effectOnSuccess: { S: 5 },
          ruleText: "Reduce difficulty of investigation",
        },
      ],
      complications: [
        "Sleeper agent",
        "Market Quarter",
        "Guard surveillance",
        "Bramblecourt backstreets",
      ],
      ties: [
        "Ember Cell",
        "Haven Cell",
        "Sleeper Agent Bureau",
        "Lanternward",
        "Bramblecourt",
      ],
      availabilityOppression: "High",
      availabilitySecondary: { track: "S", requirement: "Med" },
    },
    player: {
      title: "Sleeper Trace Protocol",
      hook: "A pattern emerges: coded market receipts, misaligned alley markers, and a sudden shift in Guard foot patrols in Lanternward. Rose believes a sleeper agent has been activated. Your team must follow subtle missteps through Bramblecourt's maze-like backstreets to identify the mole before they pinpoint the Sword's safehouses.",
    },
  },
  {
    gm: {
      id: "silent-river-crossing",
      title: "Silent River Crossing",
      category: "Secrecy",
      hook: "The purified underground river beneath Aetherbridge runs dark and slow tonight. Underflow scouts report a shuttered research safehouse on the far bank containing records on planar breaches — records the Guard wants erased. With secrecy high, now is your only chance to slip across Myco-Falls, move past glowing fungal curtains, and retrieve the last intact notes.",
      costR: 0,
      success: { H: 5, S: 5 },
      failure: { S: -5 },
      failureNotes: "–Secrecy → major lockdown",
      optionalInvestments: [
        { label: "River skiff", costR: 2, effectOnSuccess: { S: 5 } },
        {
          label: "Environmental harmonizer",
          costR: 3,
          effectOnSuccess: { S: 5 },
          ruleText: "Ignore first failed Stealth roll",
        },
      ],
      complications: [
        "Patrol lockdown",
        "Sewer river",
        "Safehouse security",
        "Myco-Falls fungal curtains",
      ],
      ties: [
        "Underflow Cell",
        "Arcano-Engine Guild (remnants)",
        "City Guard elite division",
        "Aetherbridge",
        "Myco-Falls",
      ],
      availabilityOppression: "High",
      availabilitySecondary: { track: "S", requirement: "High" },
    },
    player: {
      title: "Silent River Crossing",
      hook: "The purified underground river beneath Aetherbridge runs dark and slow tonight. Underflow scouts report a shuttered research safehouse on the far bank containing records on planar breaches — records the Guard wants erased. With secrecy high, now is your only chance to slip across Myco-Falls, move past glowing fungal curtains, and retrieve the last intact notes.",
    },
  },

  // GRID 2: HOPE + OPPRESSION (9 missions)
  {
    gm: {
      id: "dimming-hearths",
      title: "The Dimming Hearths",
      category: "Propaganda",
      hook: "Rumors from Bramblecourt's stacked tenements speak of families losing faith after a recent Guild quota hike. Haven Cell supports are stretched thin. Elijah sends your team to deliver medical stabilizers and food, but more importantly, to remind them they're not forgotten. The Guard exploits despair — and despair spreads like mold.",
      costR: 0,
      success: { H: 5 },
      failure: { H: -5 },
      optionalInvestments: [
        { label: "Supplies", costR: 1, effectOnSuccess: { H: 5 } },
        {
          label: "Extra medics",
          costR: 2,
          effectOnSuccess: { H: 5 },
          ruleText: "Boost morale impact",
        },
      ],
      complications: [
        "Guard patrols",
        "Despair",
        "Resource scarcity",
        "Bramblecourt tenements",
      ],
      ties: ["Haven Cell", "Industrial Compliance Board", "Bramblecourt"],
      availabilityOppression: "Low",
      availabilitySecondary: { track: "H", requirement: "Low" },
    },
    player: {
      title: "The Dimming Hearths",
      hook: "Rumors from Bramblecourt's stacked tenements speak of families losing faith after a recent Guild quota hike. Haven Cell supports are stretched thin. Elijah sends your team to deliver medical stabilizers and food, but more importantly, to remind them they're not forgotten. The Guard exploits despair — and despair spreads like mold.",
    },
  },
  {
    gm: {
      id: "chalk-pavements",
      title: "Chalk the Pavements",
      category: "Propaganda",
      hook: "Lanternward's market stones are still damp from last night's rain. With hope rising, Haven artisans propose marking the plazas with chalk sigils representing unity. The markings are harmless, symbolic — but illegal. If spotted, the Guard may erase them violently. Your team must move fast, distract watchers, and leave the streets whispering of courage.",
      costR: 0,
      success: { H: 5 },
      failure: { S: -5 },
      failureNotes: "Caught chalking → –Secrecy",
      optionalInvestments: [
        { label: "Pigment kits", costR: 1, effectOnSuccess: { H: 5 } },
        {
          label: "Lookout network",
          costR: 2,
          effectOnSuccess: { H: 5 },
          ruleText: "Reduce detection risk",
        },
      ],
      complications: [
        "Guard patrols",
        "Market surveillance",
        "Witnesses",
        "Lanternward market stones",
      ],
      ties: ["Haven Cell", "Lanternward civilians", "Lanternward"],
      availabilityOppression: "Low",
      availabilitySecondary: { track: "H", requirement: "Med" },
    },
    player: {
      title: "Chalk the Pavements",
      hook: "Lanternward's market stones are still damp from last night's rain. With hope rising, Haven artisans propose marking the plazas with chalk sigils representing unity. The markings are harmless, symbolic — but illegal. If spotted, the Guard may erase them violently. Your team must move fast, distract watchers, and leave the streets whispering of courage.",
    },
  },
  {
    gm: {
      id: "lantern-choir-gathering",
      title: "Lantern Choir Gathering",
      category: "Propaganda",
      hook: "A rare convergence of optimism sweeps Lanternward — street performers risk playing again, and neighbors exchange bread freely. Haven Cell wants to kindle it into a coordinated lantern-lighting along the riverbanks beneath Aetherbridge, echoing old festival rites. Guard retaliation is possible, but if this moment blooms, the entire city will feel its warmth.",
      costR: 0,
      success: { H: 5, U: 5 },
      failure: { H: -5 },
      failureNotes: "Minor → –Hope",
      optionalInvestments: [
        { label: "Lanterns", costR: 1, effectOnSuccess: { H: 5 } },
        { label: "Performers", costR: 2, effectOnSuccess: { H: 5 } },
        {
          label: "Portable light shields",
          costR: 3,
          effectOnSuccess: { H: 5 },
          ruleText: "Reduce detection risk",
        },
      ],
      complications: [
        "Guard patrols",
        "Riverside security",
        "Visibility",
        "Aetherbridge riverbanks",
      ],
      ties: ["Haven Cell", "Civilians", "Lanternward", "Aetherbridge"],
      availabilityOppression: "Low",
      availabilitySecondary: { track: "H", requirement: "High" },
    },
    player: {
      title: "Lantern Choir Gathering",
      hook: "A rare convergence of optimism sweeps Lanternward — street performers risk playing again, and neighbors exchange bread freely. Haven Cell wants to kindle it into a coordinated lantern-lighting along the riverbanks beneath Aetherbridge, echoing old festival rites. Guard retaliation is possible, but if this moment blooms, the entire city will feel its warmth.",
    },
  },
  {
    gm: {
      id: "save-vanishing-voices",
      title: "Save the Vanishing Voices",
      category: "Smuggling",
      hook: "Council's Reach is quietly funneling dissidents into 'Re-Education Caravans.' One wagon leaves Bramblecourt tonight carrying three civilians who dared speak openly. Haven Cell begs for intervention before they disappear into the northern camps. Underflow scouts have the route… but only Ember Cell can pull off the snatch.",
      costR: 0,
      success: { H: 5 },
      failure: { H: -5, O: 1 },
      failureNotes: "–Hope, +Oppression",
      optionalInvestments: [
        {
          label: "Sabotage tools",
          costR: 1,
          effectOnSuccess: { H: 5 },
        },
        {
          label: "Decoy wagon",
          costR: 2,
          effectOnSuccess: { H: 5 },
          ruleText: "Reduce difficulty of extraction",
        },
      ],
      complications: [
        "Guard transport",
        "Re-Education facility",
        "Prisoners",
        "Northern camps",
      ],
      ties: [
        "Haven Cell",
        "Ember Cell",
        "City Guard Transport Division",
        "Bramblecourt",
        "Council's Reach",
      ],
      availabilityOppression: "Med",
      availabilitySecondary: { track: "H", requirement: "Low" },
    },
    player: {
      title: "Save the Vanishing Voices",
      hook: "Council's Reach is quietly funneling dissidents into 'Re-Education Caravans.' One wagon leaves Bramblecourt tonight carrying three civilians who dared speak openly. Haven Cell begs for intervention before they disappear into the northern camps. Underflow scouts have the route… but only Ember Cell can pull off the snatch.",
    },
  },
  {
    gm: {
      id: "candles-balconies",
      title: "Candles on the Balconies",
      category: "Propaganda",
      hook: "A quiet, coordinated act of rebellion: at midnight, Lanternward and Bramblecourt residents will place candles on their windowsills to honor those taken by the Guard. The People's Sword must secure safe passage for runners distributing candles and ensure the Guard doesn't cut the lights early.",
      costR: 0,
      success: { H: 5 },
      failure: { S: -5 },
      failureNotes: "–Secrecy",
      optionalInvestments: [
        { label: "Wax stock", costR: 1, effectOnSuccess: { H: 5 } },
        {
          label: "Cloaks and hoods",
          costR: 2,
          effectOnSuccess: { H: 5 },
          ruleText: "Increase participation and impact",
        },
      ],
      complications: [
        "Guard patrols",
        "Coordination",
        "Detection risk",
        "Lanternward and Bramblecourt",
      ],
      ties: [
        "Haven Cell",
        "Civilians",
        "Guard patrols",
        "Lanternward",
        "Bramblecourt",
      ],
      availabilityOppression: "Med",
      availabilitySecondary: { track: "H", requirement: "Med" },
    },
    player: {
      title: "Candles on the Balconies",
      hook: "A quiet, coordinated act of rebellion: at midnight, Lanternward and Bramblecourt residents will place candles on their windowsills to honor those taken by the Guard. The People's Sword must secure safe passage for runners distributing candles and ensure the Guard doesn't cut the lights early.",
    },
  },
  {
    gm: {
      id: "rally-workers-song",
      title: "Rally the Workers' Song",
      category: "Unity",
      hook: "Blast Block workers hum an old protest ballad — banned, of course — and their courage is rising toward something dangerous. Haven and Ember Cell leaders fear the workers may riot prematurely. Your team must meet them at the Ironclad Foundry's slag courtyard, steady their hearts, and help them plan a real, strategic form of defiance.",
      costR: 0,
      success: { U: 5, H: 5 },
      failure: { U: -5 },
      failureNotes: "–Unity, crackdown → +Oppression",
      optionalInvestments: [
        { label: "Safehouse access", costR: 1, effectOnSuccess: { U: 5 } },
        {
          label: "Negotiator support",
          costR: 2,
          effectOnSuccess: { U: 5 },
          ruleText: "Reduce difficulty of diplomacy",
        },
      ],
      complications: [
        "Factory crews",
        "Guard surveillance",
        "Riot risk",
        "Ironclad Foundry",
      ],
      ties: [
        "Haven Cell",
        "Ember Cell",
        "Ironclad Foundry",
        "Blast Block workers",
      ],
      availabilityOppression: "Med",
      availabilitySecondary: { track: "H", requirement: "High" },
    },
    player: {
      title: "Rally the Workers' Song",
      hook: "Blast Block workers hum an old protest ballad — banned, of course — and their courage is rising toward something dangerous. Haven and Ember Cell leaders fear the workers may riot prematurely. Your team must meet them at the Ironclad Foundry's slag courtyard, steady their hearts, and help them plan a real, strategic form of defiance.",
    },
  },
  {
    gm: {
      id: "shadows-bread-line",
      title: "Shadows in the Bread Line",
      category: "Propaganda",
      hook: "Guard officers in Bramblecourt have shortened ration distribution, sparking claws-out infighting among desperate families. Haven Cell needs your team to keep peace long enough for Underflow runners to slip in spare sacks from the Overflow Vaults. If this line breaks, it becomes a riot — and a perfect excuse for martial crackdowns.",
      costR: 0,
      success: { H: 5 },
      failure: { H: -5, O: 1 },
      failureNotes: "–Hope, +Oppression",
      optionalInvestments: [
        { label: "Food sacks", costR: 1, effectOnSuccess: { H: 5 } },
        {
          label: "Supply crate drop",
          costR: 3,
          effectOnSuccess: { H: 5 },
          ruleText: "Significantly boost morale",
        },
      ],
      complications: [
        "Bread lines",
        "Despair",
        "Guard exploitation",
        "Overflow Vaults",
      ],
      ties: [
        "Haven Cell",
        "Underflow Cell",
        "Guard Food Oversight Patrol",
        "Bramblecourt",
        "Overflow Vaults",
      ],
      availabilityOppression: "High",
      availabilitySecondary: { track: "H", requirement: "Low" },
    },
    player: {
      title: "Shadows in the Bread Line",
      hook: "Guard officers in Bramblecourt have shortened ration distribution, sparking claws-out infighting among desperate families. Haven Cell needs your team to keep peace long enough for Underflow runners to slip in spare sacks from the Overflow Vaults. If this line breaks, it becomes a riot — and a perfect excuse for martial crackdowns.",
    },
  },
  {
    gm: {
      id: "nightward-stories",
      title: "Nightward Stories",
      category: "Propaganda",
      hook: "In Lanternward, elders remember stories the Council has tried to erase — tales of solidarity and seasons of renewal. Haven Cell asks you to escort traveling storytellers between hidden basements. Each tale rekindles a spark the Guard despises. If even one storyteller is taken, fear spreads like frost.",
      costR: 0,
      success: { H: 5, U: 5 },
      failure: { H: -5 },
      failureNotes: "Storyteller arrested → –Hope",
      optionalInvestments: [
        {
          label: "Safehouse certificates",
          costR: 1,
          effectOnSuccess: { H: 5 },
        },
        {
          label: "Escort detail",
          costR: 2,
          effectOnSuccess: { H: 5 },
          ruleText: "Protect storytellers from arrest",
        },
      ],
      complications: [
        "Guard patrols",
        "Storyteller safety",
        "Basement security",
        "Cultural Suppression Unit",
      ],
      ties: [
        "Haven Cell",
        "Civilians",
        "Guard Cultural Suppression Unit",
        "Lanternward",
      ],
      availabilityOppression: "High",
      availabilitySecondary: { track: "H", requirement: "Med" },
    },
    player: {
      title: "Nightward Stories",
      hook: "In Lanternward, elders remember stories the Council has tried to erase — tales of solidarity and seasons of renewal. Haven Cell asks you to escort traveling storytellers between hidden basements. Each tale rekindles a spark the Guard despises. If even one storyteller is taken, fear spreads like frost.",
    },
  },
  {
    gm: {
      id: "strike-beacon-tower",
      title: "Strike the Beacon Tower",
      category: "Secrecy",
      hook: "The Beacon Tower in Council's Reach broadcasts Council propaganda endlessly, washing the city in fear. Now, buoyed by a rising tide of hope, Ember Cell proposes a bold strike. Bring the tower down — not quietly, but symbolically — and let the shockwave ripple through all five districts. Every civilian who sees the sparks fall will remember the Sword.",
      costR: 0,
      success: { H: 10, O: -1 },
      failure: { O: 1, S: -5 },
      failureNotes: "+Oppression (major), –Secrecy",
      optionalInvestments: [
        { label: "Explosives", costR: 2, effectOnSuccess: { H: 5 } },
        {
          label: "Coordinated multi-cell strike",
          costR: 3,
          effectOnSuccess: { H: 5 },
          ruleText: "Reduce difficulty and increase impact",
        },
      ],
      complications: [
        "Beacon tower security",
        "Guard response",
        "City-wide impact",
        "All five districts",
      ],
      ties: [
        "Ember Cell",
        "Underflow Cell",
        "City Guard Propaganda Bureau",
        "Council's Reach",
      ],
      availabilityOppression: "High",
      availabilitySecondary: { track: "H", requirement: "High" },
    },
    player: {
      title: "Strike the Beacon Tower",
      hook: "The Beacon Tower in Council's Reach broadcasts Council propaganda endlessly, washing the city in fear. Now, buoyed by a rising tide of hope, Ember Cell proposes a bold strike. Bring the tower down — not quietly, but symbolically — and let the shockwave ripple through all five districts. Every civilian who sees the sparks fall will remember the Sword.",
    },
  },

  // GRID 3: UNITY + OPPRESSION (9 missions)
  {
    gm: {
      id: "soot-scars-mediation",
      title: "Soot & Scars Mediation",
      category: "Unity",
      hook: "Two small Sword teams clashed over scarce toolkits distributed by the Emberforge Compact. Tempers flared; accusations were shouted. If this fracture spreads, both teams will hesitate in critical moments. Elijah asks your team to mediate before the split becomes permanent.",
      costR: 0,
      success: { U: 5 },
      failure: { U: -5 },
      optionalInvestments: [
        { label: "Neutral venue", costR: 1, effectOnSuccess: { U: 5 } },
        {
          label: "Mediator tokens",
          costR: 2,
          effectOnSuccess: { U: 5 },
          ruleText: "Reduce difficulty of mediation",
        },
      ],
      complications: [
        "Cell conflict",
        "Resource disputes",
        "Trust issues",
        "Emberforge Compact",
      ],
      ties: ["Haven Cell mediators", "Ember Cell", "Emberforge Compact"],
      availabilityOppression: "Low",
      availabilitySecondary: { track: "U", requirement: "Low" },
    },
    player: {
      title: "Soot & Scars Mediation",
      hook: "Two small Sword teams clashed over scarce toolkits distributed by the Emberforge Compact. Tempers flared; accusations were shouted. If this fracture spreads, both teams will hesitate in critical moments. Elijah asks your team to mediate before the split becomes permanent.",
    },
  },
  {
    gm: {
      id: "coop-cart-run",
      title: "Co-Op Cart Run",
      category: "Smuggling",
      hook: "A coordinated supply run across Lanternward requires three Sword teams to share a single cart route — a delicate dance through narrow Bramblecourt alleys. Underflow scouts have the timing, but trust between teams is still shallow. Escort the cart, smooth tensions, and show everyone the Sword moves better together.",
      costR: 0,
      success: { U: 5 },
      failure: { U: -5 },
      optionalInvestments: [
        { label: "Mule rental", costR: 1, effectOnSuccess: { U: 5 } },
        {
          label: "Upgraded maps",
          costR: 2,
          effectOnSuccess: { U: 5 },
          ruleText: "Reduce risk and improve coordination",
        },
      ],
      complications: [
        "Coordination",
        "Guard patrols",
        "Supply routes",
        "Bramblecourt alleys",
      ],
      ties: ["Haven Cell", "Underflow Cell", "Lanternward", "Bramblecourt"],
      availabilityOppression: "Low",
      availabilitySecondary: { track: "U", requirement: "Med" },
    },
    player: {
      title: "Co-Op Cart Run",
      hook: "A coordinated supply run across Lanternward requires three Sword teams to share a single cart route — a delicate dance through narrow Bramblecourt alleys. Underflow scouts have the timing, but trust between teams is still shallow. Escort the cart, smooth tensions, and show everyone the Sword moves better together.",
    },
  },
  {
    gm: {
      id: "three-cell-roundtable",
      title: "The Three-Cell Roundtable",
      category: "Unity",
      hook: "Unity is strong, and the moment is right: Haven, Underflow, and Ember representatives wish to meet in the Overflow Vaults, where tunnels echo with quiet safety. The goal is to draft a long-term resistance plan touching all five districts. Your role: keep the meeting secret, secure, and focused.",
      costR: 0,
      success: { U: 5 },
      failure: { S: -5 },
      failureNotes: "–Secrecy",
      optionalInvestments: [
        {
          label: "Encrypted comm beads",
          costR: 1,
          effectOnSuccess: { U: 5 },
        },
        {
          label: "Sound-baffling fabric",
          costR: 2,
          effectOnSuccess: { U: 5 },
          ruleText: "Reduce detection risk",
        },
      ],
      complications: [
        "Leader coordination",
        "Hidden workshop",
        "Guard surveillance",
        "Overflow Vaults",
      ],
      ties: [
        "All People's Sword Cells",
        "Haven Cell",
        "Underflow Cell",
        "Ember Cell",
        "Overflow Vaults",
      ],
      availabilityOppression: "Low",
      availabilitySecondary: { track: "U", requirement: "High" },
    },
    player: {
      title: "The Three-Cell Roundtable",
      hook: "Unity is strong, and the moment is right: Haven, Underflow, and Ember representatives wish to meet in the Overflow Vaults, where tunnels echo with quiet safety. The goal is to draft a long-term resistance plan touching all five districts. Your role: keep the meeting secret, secure, and focused.",
    },
  },
  {
    gm: {
      id: "fractured-forge",
      title: "The Fractured Forge",
      category: "Unity",
      hook: "The Ironclad Foundry workers aligned with the Sword are refusing to share tools after a string of paranoia-inducing inspections by the Industrial Compliance Board. Their refusal threatens Ember Cell's next operation. Mend the divide and convince the smiths their survival depends on cooperation.",
      costR: 0,
      success: { U: 5 },
      failure: { U: -5 },
      optionalInvestments: [
        { label: "Tool replacements", costR: 1, effectOnSuccess: { U: 5 } },
        {
          label: "Mediator support",
          costR: 2,
          effectOnSuccess: { U: 5 },
          ruleText: "Reduce difficulty of resolution",
        },
      ],
      complications: [
        "Smiths vs mechanics",
        "Gear maintenance",
        "Internal conflict",
        "Industrial Compliance Board",
      ],
      ties: ["Ember Cell", "Ironclad Foundry Guild", "Ironclad Foundry"],
      availabilityOppression: "Med",
      availabilitySecondary: { track: "U", requirement: "Low" },
    },
    player: {
      title: "The Fractured Forge",
      hook: "The Ironclad Foundry workers aligned with the Sword are refusing to share tools after a string of paranoia-inducing inspections by the Industrial Compliance Board. Their refusal threatens Ember Cell's next operation. Mend the divide and convince the smiths their survival depends on cooperation.",
    },
  },
  {
    gm: {
      id: "parallel-strikes-coordination",
      title: "Parallel Strikes Coordination",
      category: "Unity",
      hook: "Two sword teams plan synchronized acts in Bramblecourt and Lanternward to strain Guard resources. The timing must be perfect, and trust absolute. You'll act as the central relay, coordinating signals through Underflow routes running beneath the Lower Siphonworks.",
      costR: 0,
      success: { U: 5, O: -1 },
      failure: { U: -5 },
      optionalInvestments: [
        { label: "Comm runners", costR: 2, effectOnSuccess: { U: 5 } },
        {
          label: "Relay harmonizers",
          costR: 3,
          effectOnSuccess: { U: 5 },
          ruleText: "Improve coordination and timing",
        },
      ],
      complications: [
        "Synchronization",
        "Guard response",
        "Cell coordination",
        "Lower Siphonworks",
      ],
      ties: ["Ember Cell", "Underflow Cell", "Bramblecourt", "Lanternward"],
      availabilityOppression: "Med",
      availabilitySecondary: { track: "U", requirement: "Med" },
    },
    player: {
      title: "Parallel Strikes Coordination",
      hook: "Two sword teams plan synchronized acts in Bramblecourt and Lanternward to strain Guard resources. The timing must be perfect, and trust absolute. You'll act as the central relay, coordinating signals through Underflow routes running beneath the Lower Siphonworks.",
    },
  },
  {
    gm: {
      id: "union-lanterns",
      title: "Union of the Lanterns",
      category: "Unity",
      hook: "Unity is peaking. A symbolic ritual performed by multiple Sword teams — a lantern-lighting beneath Myco-Falls — will reaffirm shared purpose. Haven Cell has prepared the space; Underflow has secured entry tunnels. Ensure the ritual proceeds uninterrupted.",
      costR: 0,
      success: { U: 10 },
      failure: { S: -5 },
      failureNotes: "–Secrecy",
      optionalInvestments: [
        { label: "Ceremonial items", costR: 1, effectOnSuccess: { U: 5 } },
        {
          label: "Travel protection",
          costR: 2,
          effectOnSuccess: { U: 5 },
          ruleText: "Reduce detection risk",
        },
      ],
      complications: [
        "Distant cells",
        "Clandestine ritual",
        "Guard surveillance",
        "Myco-Falls",
      ],
      ties: ["Haven Cell", "Underflow Cell", "Ember Cell", "Myco-Falls"],
      availabilityOppression: "Med",
      availabilitySecondary: { track: "U", requirement: "High" },
    },
    player: {
      title: "Union of the Lanterns",
      hook: "Unity is peaking. A symbolic ritual performed by multiple Sword teams — a lantern-lighting beneath Myco-Falls — will reaffirm shared purpose. Haven Cell has prepared the space; Underflow has secured entry tunnels. Ensure the ritual proceeds uninterrupted.",
    },
  },
  {
    gm: {
      id: "stop-spiral",
      title: "Stop the Spiral",
      category: "Unity",
      hook: "Under intense Guard pressure, an Ember team is collapsing — blaming each other for a failed strike in Aetherbridge. If they dissolve now, the Sword loses critical infiltration talent. Haven mediators can't reach them, so your neutral team must break through the guilt, anger, and paranoia.",
      costR: 0,
      success: { U: 5 },
      failure: { U: -10, O: 1 },
      failureNotes: "–Unity (major), +Oppression",
      optionalInvestments: [
        { label: "Peacekeeper escort", costR: 1, effectOnSuccess: { U: 5 } },
        {
          label: "Safehouse refuge",
          costR: 2,
          effectOnSuccess: { U: 5 },
          ruleText: "Provide stability and safety",
        },
      ],
      complications: [
        "Cell collapse",
        "Internal stress",
        "Fracture risk",
        "Aetherbridge",
      ],
      ties: ["Haven Cell", "Ember Cell", "Aetherbridge"],
      availabilityOppression: "High",
      availabilitySecondary: { track: "U", requirement: "Low" },
    },
    player: {
      title: "Stop the Spiral",
      hook: "Under intense Guard pressure, an Ember team is collapsing — blaming each other for a failed strike in Aetherbridge. If they dissolve now, the Sword loses critical infiltration talent. Haven mediators can't reach them, so your neutral team must break through the guilt, anger, and paranoia.",
    },
  },
  {
    gm: {
      id: "tide-line",
      title: "Tide the Line",
      category: "Unity",
      hook: "During peak oppression, courier routes across Bramblecourt become lethal. Underflow has proposed a three-team chain relay to move intel from Aetherbridge to Lanternward without any one runner taking all the risk. You must oversee the chain, intervene when danger spikes, and maintain morale.",
      costR: 0,
      success: { U: 5, S: 5 },
      failure: { U: -5 },
      optionalInvestments: [
        { label: "Extra couriers", costR: 1, effectOnSuccess: { U: 5 } },
        {
          label: "Decoys",
          costR: 2,
          effectOnSuccess: { U: 5 },
          ruleText: "Reduce risk and improve success",
        },
      ],
      complications: [
        "Dangerous districts",
        "Emergency coordination",
        "Guard patrols",
        "Courier routes",
      ],
      ties: [
        "Underflow Cell",
        "Haven Cell",
        "Aetherbridge",
        "Lanternward",
        "Bramblecourt",
      ],
      availabilityOppression: "High",
      availabilitySecondary: { track: "U", requirement: "Med" },
    },
    player: {
      title: "Tide the Line",
      hook: "During peak oppression, courier routes across Bramblecourt become lethal. Underflow has proposed a three-team chain relay to move intel from Aetherbridge to Lanternward without any one runner taking all the risk. You must oversee the chain, intervene when danger spikes, and maintain morale.",
    },
  },
  {
    gm: {
      id: "conclave-dark",
      title: "The Conclave in the Dark",
      category: "Unity",
      hook: "All three branches of the People's Sword seek to gather in a forgotten chamber beneath the Greenlight Basin — a place thick with arcano-tech residue. The meeting is historic, dangerous, and vital. Guard intel pressures the walls; sleeper networks feel active; the city itself holds its breath. Ensure no one follows, no one listens, and the Sword emerges unified.",
      costR: 0,
      success: { U: 10 },
      failure: { S: -5 },
      failureNotes: "–Secrecy, Guard crackdown",
      optionalInvestments: [
        {
          label: "Encrypted comm sets",
          costR: 2,
          effectOnSuccess: { U: 5 },
        },
        {
          label: "Overwatch team",
          costR: 3,
          effectOnSuccess: { U: 5 },
          ruleText: "Protect meeting from Guard crackdown",
        },
      ],
      complications: [
        "Major cells",
        "Strategy meeting",
        "Guard crackdown risk",
        "Greenlight Basin",
      ],
      ties: [
        "Haven Cell",
        "Underflow Cell",
        "Ember Cell",
        "City Guard Intelligence",
        "Sleeper Networks",
        "Greenlight Basin",
      ],
      availabilityOppression: "High",
      availabilitySecondary: { track: "U", requirement: "High" },
    },
    player: {
      title: "The Conclave in the Dark",
      hook: "All three branches of the People's Sword seek to gather in a forgotten chamber beneath the Greenlight Basin — a place thick with arcano-tech residue. The meeting is historic, dangerous, and vital. Guard intel pressures the walls; sleeper networks feel active; the city itself holds its breath. Ensure no one follows, no one listens, and the Sword emerges unified.",
    },
  },

  // ADDITIONAL MISSIONS 28-50
  {
    gm: {
      id: "arc-light-severance",
      title: "Arc-Light Severance",
      category: "Secrecy",
      hook: "Aetherbridge's planar waste vents periodically emit unstable arc-light energy — the Guard uses this to power their anti-magic wards. Ember Cell wants to cut the conduit before the Council enacts a citywide scanning ritual. The vents pulse with dangerous arc-light, and tampering during a surge could incinerate half a block.",
      costR: 0,
      success: { O: -1 },
      failure: { O: 1 },
      optionalInvestments: [
        {
          label: "Arc-light dampening gear",
          costR: 1,
          effectOnSuccess: { O: -1 },
        },
        {
          label: "Surge timing device",
          costR: 2,
          effectOnSuccess: { O: -1 },
          ruleText: "Reduce risk of arc-light surge",
        },
      ],
      complications: [
        "Arc-light surges",
        "Guard anti-magic wards",
        "Citywide scanning ritual",
        "Aetherbridge vents",
      ],
      ties: [
        "Ember Cell",
        "Arcano-Engine Guild",
        "Guard Arc-Light Ward Unit",
        "Aetherbridge",
      ],
      availabilityOppression: "Med–High",
      availabilitySecondary: { track: "S", requirement: "Low–Med" },
    },
    player: {
      title: "Arc-Light Severance",
      hook: "Aetherbridge's planar waste vents periodically emit unstable arc-light energy — the Guard uses this to power their anti-magic wards. Ember Cell wants to cut the conduit before the Council enacts a citywide scanning ritual. The vents pulse with dangerous arc-light, and tampering during a surge could incinerate half a block.",
    },
  },
  {
    gm: {
      id: "coppercoil-purge",
      title: "The Coppercoil Purge",
      category: "Secrecy",
      hook: "In the sublevels of the Coppercoil Refinery in Blast Block, the Guard stores its mechanized surveyor drones before deployment. Disable enough drones in their charging nests to blind patrol paths for a week. But once the refinery klaxons trigger, the entire district locks down.",
      costR: 0,
      success: { S: 5 },
      failure: { S: -5 },
      optionalInvestments: [
        {
          label: "Drone disabling tools",
          costR: 1,
          effectOnSuccess: { S: 5 },
        },
        {
          label: "Klaxon suppression device",
          costR: 2,
          effectOnSuccess: { S: 5 },
          ruleText: "Prevent district lockdown",
        },
      ],
      complications: [
        "Refinery security",
        "Mechanized drones",
        "District lockdown",
        "Coppercoil Refinery",
      ],
      ties: [
        "Ember Cell",
        "Ironclad Foundry",
        "Mechanical Surveyor Corps",
        "Blast Block",
      ],
      availabilityOppression: "High",
      availabilitySecondary: { track: "S", requirement: "Med–High" },
    },
    player: {
      title: "The Coppercoil Purge",
      hook: "In the sublevels of the Coppercoil Refinery in Blast Block, the Guard stores its mechanized surveyor drones before deployment. Disable enough drones in their charging nests to blind patrol paths for a week. But once the refinery klaxons trigger, the entire district locks down.",
    },
  },
  {
    gm: {
      id: "ghost-relay-chain",
      title: "Ghost in the Relay Chain",
      category: "Secrecy",
      hook: "A networked arcano-tech relay in Bramblecourt can be backfed with a false identity signature, tricking Guard scans for days. Underflow scouts found the entry node, but inserting the signature requires crawling a ventilation crawlspace no bigger than a coffin.",
      costR: 0,
      success: { S: 5 },
      failure: { S: -5 },
      optionalInvestments: [
        {
          label: "False identity signature",
          costR: 1,
          effectOnSuccess: { S: 5 },
        },
        {
          label: "Ventilation mapping",
          costR: 2,
          effectOnSuccess: { S: 5 },
          ruleText: "Reduce difficulty of crawlspace navigation",
        },
      ],
      complications: [
        "Tight crawlspace",
        "Guard scans",
        "Relay security",
        "Bramblecourt",
      ],
      ties: ["Underflow Cell", "Ember Cell", "Relay Division", "Bramblecourt"],
      availabilityOppression: "Med",
      availabilitySecondary: { track: "S", requirement: "High" },
    },
    player: {
      title: "Ghost in the Relay Chain",
      hook: "A networked arcano-tech relay in Bramblecourt can be backfed with a false identity signature, tricking Guard scans for days. Underflow scouts found the entry node, but inserting the signature requires crawling a ventilation crawlspace no bigger than a coffin.",
    },
  },
  {
    gm: {
      id: "residuum-rumbling",
      title: "Residuum Rumbling",
      category: "Secrecy",
      hook: "A storage vault of planar residuum has been left unsupervised in Aetherbridge after a failed experiment. The Council intends to repurpose it for new suppressive measures. Steal or destroy the crates before the Industrial Compliance Board collects them.",
      costR: 0,
      success: { H: 5 },
      failure: { O: 1 },
      optionalInvestments: [
        {
          label: "Residuum containment gear",
          costR: 1,
          effectOnSuccess: { H: 5 },
        },
        {
          label: "Sabotage charges",
          costR: 2,
          effectOnSuccess: { H: 5 },
          ruleText: "Destroy residuum if extraction fails",
        },
      ],
      complications: [
        "Unsupervised vault",
        "Industrial Compliance Board",
        "Planar residuum",
        "Aetherbridge",
      ],
      ties: [
        "Ember Cell",
        "Arcano-Engine Guild",
        "Industrial Compliance Board",
        "Aetherbridge",
      ],
      availabilityOppression: "Low–Med",
      availabilitySecondary: { track: "S", requirement: "Low" },
    },
    player: {
      title: "Residuum Rumbling",
      hook: "A storage vault of planar residuum has been left unsupervised in Aetherbridge after a failed experiment. The Council intends to repurpose it for new suppressive measures. Steal or destroy the crates before the Industrial Compliance Board collects them.",
    },
  },
  {
    gm: {
      id: "crack-copperline-cache",
      title: "Crack the Copperline Cache",
      category: "Secrecy",
      hook: "The Guard has installed copperline sensory threads beneath Lanternward's major boulevards. Cutting them requires precise timing and zero vibrations — a perfect job for Ember/Underflow teams working together.",
      costR: 0,
      success: { S: 5 },
      failure: { U: -5 },
      optionalInvestments: [
        {
          label: "Precision cutting tools",
          costR: 1,
          effectOnSuccess: { S: 5 },
        },
        {
          label: "Vibration dampeners",
          costR: 2,
          effectOnSuccess: { S: 5 },
          ruleText: "Reduce risk of detection",
        },
      ],
      complications: [
        "Copperline threads",
        "Precise timing",
        "Vibration detection",
        "Lanternward boulevards",
      ],
      ties: [
        "Underflow Cell",
        "Ember Cell",
        "Guard Sensory Division",
        "Lanternward",
      ],
      availabilityOppression: "Med",
      availabilitySecondary: { track: "S", requirement: "Med" },
    },
    player: {
      title: "Crack the Copperline Cache",
      hook: "The Guard has installed copperline sensory threads beneath Lanternward's major boulevards. Cutting them requires precise timing and zero vibrations — a perfect job for Ember/Underflow teams working together.",
    },
  },
  {
    gm: {
      id: "petal-run",
      title: "The Petal Run",
      category: "Propaganda",
      hook: "Lanternward's florists harvest moon-petals that glow under sewer biolume. Haven Cell proposes scattering petals at key intersections to mark safe routes. The act is beautiful and quiet — but the Guard calls it 'symbolic incitement.'",
      costR: 0,
      success: { H: 5 },
      failure: { S: -5 },
      optionalInvestments: [
        {
          label: "Moon-petals",
          costR: 1,
          effectOnSuccess: { H: 5 },
        },
        {
          label: "Florist network",
          costR: 2,
          effectOnSuccess: { H: 5 },
          ruleText: "Increase coverage and impact",
        },
      ],
      complications: [
        "Guard patrols",
        "Symbolic incitement charges",
        "Key intersections",
        "Lanternward",
      ],
      ties: ["Haven Cell", "Civilians", "Lanternward florists", "Lanternward"],
      availabilityOppression: "Low–Med",
      availabilitySecondary: { track: "H", requirement: "Med–High" },
    },
    player: {
      title: "The Petal Run",
      hook: "Lanternward's florists harvest moon-petals that glow under sewer biolume. Haven Cell proposes scattering petals at key intersections to mark safe routes. The act is beautiful and quiet — but the Guard calls it 'symbolic incitement.'",
    },
  },
  {
    gm: {
      id: "festival-echoes-revived",
      title: "Festival of Echoes (Revived)",
      category: "Propaganda",
      hook: "Elkin's oldest festival honored the city's founding river — now forbidden. Haven Cell suggests a secret revival beneath The Quiet Steps. Drumming echoes, whispered songs, and lantern reflections could unify thousands emotionally. If caught, it will be considered sedition.",
      costR: 0,
      success: { H: 5, U: 5 },
      failure: { H: -5 },
      optionalInvestments: [
        {
          label: "Festival supplies",
          costR: 1,
          effectOnSuccess: { H: 5 },
        },
        {
          label: "Sound dampening",
          costR: 2,
          effectOnSuccess: { H: 5 },
          ruleText: "Reduce detection risk",
        },
      ],
      complications: [
        "Forbidden festival",
        "Sedition charges",
        "The Quiet Steps",
        "Guard suppression",
      ],
      ties: [
        "Haven Cell",
        "Underflow Cell",
        "Guard Suppression",
        "The Quiet Steps",
      ],
      availabilityOppression: "High",
      availabilitySecondary: { track: "H", requirement: "High" },
    },
    player: {
      title: "Festival of Echoes (Revived)",
      hook: "Elkin's oldest festival honored the city's founding river — now forbidden. Haven Cell suggests a secret revival beneath The Quiet Steps. Drumming echoes, whispered songs, and lantern reflections could unify thousands emotionally. If caught, it will be considered sedition.",
    },
  },
  {
    gm: {
      id: "sky-sketch-uprising",
      title: "Sky-Sketch Uprising",
      category: "Propaganda",
      hook: "Blast Block has huge smoke vents that billow steam clouds into the sky. A group of youths wants to project anti-Council illusions into the clouds using stolen arcano-lenses. They need escort and protection.",
      costR: 0,
      success: { H: 5 },
      failure: { S: -5 },
      optionalInvestments: [
        {
          label: "Arcano-lenses",
          costR: 1,
          effectOnSuccess: { H: 5 },
        },
        {
          label: "Protection detail",
          costR: 2,
          effectOnSuccess: { H: 5 },
          ruleText: "Protect youths from Guard response",
        },
      ],
      complications: [
        "Smoke vents",
        "Guard response",
        "Stolen equipment",
        "Blast Block",
      ],
      ties: ["Haven Cell", "Rouge arcano-artists", "Blast Block"],
      availabilityOppression: "Med",
      availabilitySecondary: { track: "H", requirement: "High" },
    },
    player: {
      title: "Sky-Sketch Uprising",
      hook: "Blast Block has huge smoke vents that billow steam clouds into the sky. A group of youths wants to project anti-Council illusions into the clouds using stolen arcano-lenses. They need escort and protection.",
    },
  },
  {
    gm: {
      id: "mother-hearths-recipe",
      title: "Mother Hearth's Recipe",
      category: "Propaganda",
      hook: "A beloved soup kitchen in Bramblecourt has closed after food confiscations. Reopening it — even for a night — would restore faith in shared humanity. Your team must gather ingredients, slip past ration checkpoints, and rekindle the hearth.",
      costR: 0,
      success: { H: 5 },
      failure: { H: -5 },
      optionalInvestments: [
        {
          label: "Ingredients",
          costR: 1,
          effectOnSuccess: { H: 5 },
        },
        {
          label: "Ration checkpoint bribes",
          costR: 2,
          effectOnSuccess: { H: 5 },
          ruleText: "Reduce difficulty of passage",
        },
      ],
      complications: [
        "Food confiscations",
        "Ration checkpoints",
        "Soup kitchen security",
        "Bramblecourt",
      ],
      ties: ["Haven Cell", "Civilians", "Bramblecourt"],
      availabilityOppression: "Low",
      availabilitySecondary: { track: "H", requirement: "Low" },
    },
    player: {
      title: "Mother Hearth's Recipe",
      hook: "A beloved soup kitchen in Bramblecourt has closed after food confiscations. Reopening it — even for a night — would restore faith in shared humanity. Your team must gather ingredients, slip past ration checkpoints, and rekindle the hearth.",
    },
  },
  {
    gm: {
      id: "storykeepers-escape",
      title: "The Storykeeper's Escape",
      category: "Propaganda",
      hook: "A storyteller known as Old Marwyn has been marked for 'cultural cleansing.' Haven Cell wants to relocate him to a safehouse via Underflow routes, but the Guard has launched a misinformation campaign to flush out anyone helping him.",
      costR: 0,
      success: { H: 5 },
      failure: { H: -5 },
      optionalInvestments: [
        {
          label: "Safehouse access",
          costR: 1,
          effectOnSuccess: { H: 5 },
        },
        {
          label: "Decoy routes",
          costR: 2,
          effectOnSuccess: { H: 5 },
          ruleText: "Counter misinformation campaign",
        },
      ],
      complications: [
        "Cultural cleansing",
        "Misinformation campaign",
        "Underflow routes",
        "Old Marwyn",
      ],
      ties: ["Haven Cell", "Underflow Cell", "Guard Cultural Suppression"],
      availabilityOppression: "High",
      availabilitySecondary: { track: "H", requirement: "Med" },
    },
    player: {
      title: "The Storykeeper's Escape",
      hook: "A storyteller known as Old Marwyn has been marked for 'cultural cleansing.' Haven Cell wants to relocate him to a safehouse via Underflow routes, but the Guard has launched a misinformation campaign to flush out anyone helping him.",
    },
  },
  {
    gm: {
      id: "three-sparks-one-flame",
      title: "Three Sparks, One Flame",
      category: "Unity",
      hook: "Three micro-teams within Ember Cell have fallen out over sabotage strategy. Bringing them together in the Overflow Vaults for a shared training demonstration can restore cohesion — but tensions may explode in the enclosed chamber.",
      costR: 0,
      success: { U: 5 },
      failure: { U: -5 },
      optionalInvestments: [
        {
          label: "Training space",
          costR: 1,
          effectOnSuccess: { U: 5 },
        },
        {
          label: "Mediator support",
          costR: 2,
          effectOnSuccess: { U: 5 },
          ruleText: "Reduce risk of conflict",
        },
      ],
      complications: [
        "Micro-team conflict",
        "Enclosed chamber",
        "Sabotage strategy dispute",
        "Overflow Vaults",
      ],
      ties: ["Ember Cell", "Haven mediators", "Overflow Vaults"],
      availabilityOppression: "Med",
      availabilitySecondary: { track: "U", requirement: "Med–High" },
    },
    player: {
      title: "Three Sparks, One Flame",
      hook: "Three micro-teams within Ember Cell have fallen out over sabotage strategy. Bringing them together in the Overflow Vaults for a shared training demonstration can restore cohesion — but tensions may explode in the enclosed chamber.",
    },
  },
  {
    gm: {
      id: "underflow-dispute-resolution",
      title: "Underflow Dispute Resolution",
      category: "Unity",
      hook: "Underflow navigators are fighting over route priority in the Lower Siphonworks. The snaking tunnels have become too contested as the Guard tightens down. A neutral team must arbitrate which routes stay open and which get collapsed.",
      costR: 0,
      success: { U: 5 },
      failure: { U: -5 },
      optionalInvestments: [
        {
          label: "Route mapping",
          costR: 1,
          effectOnSuccess: { U: 5 },
        },
        {
          label: "Arbitration support",
          costR: 2,
          effectOnSuccess: { U: 5 },
          ruleText: "Improve negotiation outcome",
        },
      ],
      complications: [
        "Route priority disputes",
        "Contested tunnels",
        "Guard pressure",
        "Lower Siphonworks",
      ],
      ties: ["Underflow Cell", "Plumber's Union", "Lower Siphonworks"],
      availabilityOppression: "Low–Med",
      availabilitySecondary: { track: "U", requirement: "Low" },
    },
    player: {
      title: "Underflow Dispute Resolution",
      hook: "Underflow navigators are fighting over route priority in the Lower Siphonworks. The snaking tunnels have become too contested as the Guard tightens down. A neutral team must arbitrate which routes stay open and which get collapsed.",
    },
  },
  {
    gm: {
      id: "oath-lanternward",
      title: "The Oath of Lanternward",
      category: "Unity",
      hook: "With oppression crushing down, Haven and Ember must collaborate on evacuation plans for Lanternward's vulnerable families. You oversee a swearing-in ritual where both cells vow protection — but sleeper agents may attempt to disrupt the ceremony.",
      costR: 0,
      success: { U: 5 },
      failure: { S: -5 },
      optionalInvestments: [
        {
          label: "Ceremony space",
          costR: 1,
          effectOnSuccess: { U: 5 },
        },
        {
          label: "Security detail",
          costR: 2,
          effectOnSuccess: { U: 5 },
          ruleText: "Protect against sleeper disruption",
        },
      ],
      complications: [
        "Sleeper agents",
        "Evacuation planning",
        "Swearing-in ritual",
        "Lanternward",
      ],
      ties: ["Haven Cell", "Ember Cell", "Sleeper Networks", "Lanternward"],
      availabilityOppression: "High",
      availabilitySecondary: { track: "U", requirement: "Med" },
    },
    player: {
      title: "The Oath of Lanternward",
      hook: "With oppression crushing down, Haven and Ember must collaborate on evacuation plans for Lanternward's vulnerable families. You oversee a swearing-in ritual where both cells vow protection — but sleeper agents may attempt to disrupt the ceremony.",
    },
  },
  {
    gm: {
      id: "bramblecourt-bridgewalk",
      title: "Bramblecourt Bridgewalk",
      category: "Unity",
      hook: "A symbolic march between two safehouses must take place across Bramblecourt's dangerously narrow bridge-streets. If all teams make the journey together without splintering or panicking, it becomes a moment of collective strength.",
      costR: 0,
      success: { U: 5 },
      failure: { U: -5 },
      optionalInvestments: [
        {
          label: "Route coordination",
          costR: 1,
          effectOnSuccess: { U: 5 },
        },
        {
          label: "Lookout network",
          costR: 2,
          effectOnSuccess: { U: 5 },
          ruleText: "Reduce risk and maintain cohesion",
        },
      ],
      complications: [
        "Narrow bridge-streets",
        "Panic risk",
        "Guard patrols",
        "Bramblecourt",
      ],
      ties: ["Haven Cell", "Underflow Cell", "Civilians", "Bramblecourt"],
      availabilityOppression: "Low–Med",
      availabilitySecondary: { track: "U", requirement: "Low–Med" },
    },
    player: {
      title: "Bramblecourt Bridgewalk",
      hook: "A symbolic march between two safehouses must take place across Bramblecourt's dangerously narrow bridge-streets. If all teams make the journey together without splintering or panicking, it becomes a moment of collective strength.",
    },
  },
  {
    gm: {
      id: "councils-reach-reconvening",
      title: "Council's Reach Reconvening",
      category: "Unity",
      hook: "A rare full conclave of Sword strategists must meet in a hidden office beneath Council's Reach — dangerously close to the lion's den. The team must ensure the office stays hidden, secure, and insulated from Guard divination sweeps.",
      costR: 0,
      success: { U: 5 },
      failure: { S: -5 },
      optionalInvestments: [
        {
          label: "Hidden office access",
          costR: 1,
          effectOnSuccess: { U: 5 },
        },
        {
          label: "Divination wards",
          costR: 2,
          effectOnSuccess: { U: 5 },
          ruleText: "Protect from Guard sweeps",
        },
      ],
      complications: [
        "Guard Intelligence",
        "Divination sweeps",
        "Lion's den proximity",
        "Council's Reach",
      ],
      ties: [
        "All People's Sword Cells",
        "Guard Intelligence",
        "Council's Reach",
      ],
      availabilityOppression: "Med–High",
      availabilitySecondary: { track: "U", requirement: "High" },
    },
    player: {
      title: "Council's Reach Reconvening",
      hook: "A rare full conclave of Sword strategists must meet in a hidden office beneath Council's Reach — dangerously close to the lion's den. The team must ensure the office stays hidden, secure, and insulated from Guard divination sweeps.",
    },
  },
  {
    gm: {
      id: "lantern-thread-run",
      title: "The Lantern Thread Run",
      category: "Smuggling",
      hook: "A crucial Underflow courier route runs along the Lantern Thread, a pale-yellow glowing stream. A new Guard sensor net threatens to expose it. Your team must shepherd couriers, reroute them, and dismantle sensors before the glow-line becomes a deathtrap.",
      costR: 0,
      success: { S: 5 },
      failure: { U: -5 },
      optionalInvestments: [
        {
          label: "Sensor detection gear",
          costR: 1,
          effectOnSuccess: { S: 5 },
        },
        {
          label: "Alternative routes",
          costR: 2,
          effectOnSuccess: { S: 5 },
          ruleText: "Reroute couriers safely",
        },
      ],
      complications: [
        "Guard sensor net",
        "Courier routes",
        "Lantern Thread",
        "Glow-line exposure",
      ],
      ties: ["Underflow Cell", "Plumber's Union", "Lantern Thread"],
      availabilityOppression: "Low–Med",
      availabilitySecondary: { track: "S", requirement: "Med–High" },
    },
    player: {
      title: "The Lantern Thread Run",
      hook: "A crucial Underflow courier route runs along the Lantern Thread, a pale-yellow glowing stream. A new Guard sensor net threatens to expose it. Your team must shepherd couriers, reroute them, and dismantle sensors before the glow-line becomes a deathtrap.",
    },
  },
  {
    gm: {
      id: "stormgullet-dash",
      title: "Stormgullet Dash",
      category: "Smuggling",
      hook: "Stormgullet Causeway is unusually dry — a rare moment for cart transport. Underflow Cell wants to move a massive intelligence crate before the rains return. Guard patrols are unpredictable and echoing footsteps carry for miles.",
      costR: 0,
      success: { U: 5 },
      failure: { S: -5 },
      optionalInvestments: [
        {
          label: "Cart transport",
          costR: 1,
          effectOnSuccess: { U: 5 },
        },
        {
          label: "Sound dampening",
          costR: 2,
          effectOnSuccess: { U: 5 },
          ruleText: "Reduce echo and detection risk",
        },
      ],
      complications: [
        "Unpredictable patrols",
        "Echoing footsteps",
        "Rare dry moment",
        "Stormgullet Causeway",
      ],
      ties: ["Underflow Cell", "Haven Cell", "Stormgullet Causeway"],
      availabilityOppression: "Med",
      availabilitySecondary: { track: "S", requirement: "Low–Med" },
    },
    player: {
      title: "Stormgullet Dash",
      hook: "Stormgullet Causeway is unusually dry — a rare moment for cart transport. Underflow Cell wants to move a massive intelligence crate before the rains return. Guard patrols are unpredictable and echoing footsteps carry for miles.",
    },
  },
  {
    gm: {
      id: "greenlight-basin-harvest",
      title: "Greenlight Basin Harvest",
      category: "Smuggling",
      hook: "A strange green-glow algae blooms in the Basin — Underflow healers use it to treat exposure sickness. Collecting it is safe, but returning with it requires navigating Guard waterway inspections.",
      costR: 0,
      success: { H: 5 },
      failure: { H: -5 },
      optionalInvestments: [
        {
          label: "Harvesting gear",
          costR: 1,
          effectOnSuccess: { H: 5 },
        },
        {
          label: "Inspection bypass",
          costR: 2,
          effectOnSuccess: { H: 5 },
          ruleText: "Avoid waterway inspections",
        },
      ],
      complications: [
        "Green-glow algae",
        "Waterway inspections",
        "Exposure sickness treatment",
        "Greenlight Basin",
      ],
      ties: ["Underflow Cell", "Haven Cell", "Greenlight Basin"],
      availabilityOppression: "Low",
      availabilitySecondary: { track: "H", requirement: "Low–Med" },
    },
    player: {
      title: "Greenlight Basin Harvest",
      hook: "A strange green-glow algae blooms in the Basin — Underflow healers use it to treat exposure sickness. Collecting it is safe, but returning with it requires navigating Guard waterway inspections.",
    },
  },
  {
    gm: {
      id: "basin-breakwater-strike",
      title: "Basin Breakwater Strike",
      category: "Secrecy",
      hook: "The Guard has built breakwater barriers around the Greenlight Basin to restrict Underflow movement. If these remain intact, half of the resistance's routes are cut off. Your team must plant charges in the thigh-deep waters during the inspection rotation.",
      costR: 0,
      success: { S: 5, O: -1 },
      failure: { S: -5 },
      optionalInvestments: [
        {
          label: "Underwater charges",
          costR: 1,
          effectOnSuccess: { S: 5 },
        },
        {
          label: "Inspection rotation timing",
          costR: 2,
          effectOnSuccess: { S: 5 },
          ruleText: "Perfect timing for placement",
        },
      ],
      complications: [
        "Breakwater barriers",
        "Thigh-deep waters",
        "Inspection rotation",
        "Greenlight Basin",
      ],
      ties: ["Ember Cell", "Underflow Cell", "Greenlight Basin"],
      availabilityOppression: "High",
      availabilitySecondary: { track: "S", requirement: "Med–High" },
    },
    player: {
      title: "Basin Breakwater Strike",
      hook: "The Guard has built breakwater barriers around the Greenlight Basin to restrict Underflow movement. If these remain intact, half of the resistance's routes are cut off. Your team must plant charges in the thigh-deep waters during the inspection rotation.",
    },
  },
  {
    gm: {
      id: "myco-falls-drift-relay",
      title: "Myco-Falls Drift Relay",
      category: "Secrecy",
      hook: "A relay stone beneath Myco-Falls can broadcast coded pulses across the Underflow. The Guard is trying to tap into it. Arrive first, retune the stone, and keep the fungal curtains undisturbed — startling them releases spores that glow for hours.",
      costR: 0,
      success: { S: 5 },
      failure: { S: -5 },
      optionalInvestments: [
        {
          label: "Relay tuning tools",
          costR: 1,
          effectOnSuccess: { S: 5 },
        },
        {
          label: "Fungal curtain mapping",
          costR: 2,
          effectOnSuccess: { S: 5 },
          ruleText: "Avoid spore release",
        },
      ],
      complications: [
        "Guard tapping attempt",
        "Fungal curtains",
        "Spore release",
        "Myco-Falls",
      ],
      ties: ["Underflow Cell", "Arcano-Engine Guild (remnants)", "Myco-Falls"],
      availabilityOppression: "Med",
      availabilitySecondary: { track: "S", requirement: "High" },
    },
    player: {
      title: "Myco-Falls Drift Relay",
      hook: "A relay stone beneath Myco-Falls can broadcast coded pulses across the Underflow. The Guard is trying to tap into it. Arrive first, retune the stone, and keep the fungal curtains undisturbed — startling them releases spores that glow for hours.",
    },
  },
  {
    gm: {
      id: "ashbone-evacuation",
      title: "Ashbone Evacuation",
      category: "Smuggling",
      hook: "A makeshift refugee camp in the Ashbone stretch of Bramblecourt is about to be raided after an informant tipped the Guard. Haven Cell asks you to relocate dozens of families into Underflow routes before dawn.",
      costR: 0,
      success: { H: 5 },
      failure: { H: -5 },
      optionalInvestments: [
        {
          label: "Evacuation supplies",
          costR: 1,
          effectOnSuccess: { H: 5 },
        },
        {
          label: "Decoy routes",
          costR: 2,
          effectOnSuccess: { H: 5 },
          ruleText: "Divert Guard attention",
        },
      ],
      complications: [
        "Informant tip",
        "Dawn deadline",
        "Refugee camp",
        "Ashbone stretch",
      ],
      ties: [
        "Haven Cell",
        "Underflow Cell",
        "Informant network",
        "Bramblecourt",
      ],
      availabilityOppression: "High",
      availabilitySecondary: { track: "H", requirement: "Low–Med" },
    },
    player: {
      title: "Ashbone Evacuation",
      hook: "A makeshift refugee camp in the Ashbone stretch of Bramblecourt is about to be raided after an informant tipped the Guard. Haven Cell asks you to relocate dozens of families into Underflow routes before dawn.",
    },
  },
  {
    gm: {
      id: "bitterwell-stand-off",
      title: "Bitterwell Stand-Off",
      category: "Propaganda",
      hook: "In the Bitterwell alleys, civilians are refusing to vacate their homes despite a shutter order. Guard enforcers will arrive soon. Your team must defuse the tension, negotiate time, and prevent bloodshed.",
      costR: 0,
      success: { H: 5 },
      failure: { H: -5 },
      optionalInvestments: [
        {
          label: "Negotiation support",
          costR: 1,
          effectOnSuccess: { H: 5 },
        },
        {
          label: "Legal documentation",
          costR: 2,
          effectOnSuccess: { H: 5 },
          ruleText: "Delay Guard enforcement",
        },
      ],
      complications: [
        "Shutter order",
        "Guard enforcers",
        "Civilians refusing",
        "Bitterwell alleys",
      ],
      ties: [
        "Haven Cell",
        "Guard Housing Enforcement Unit",
        "Bitterwell alleys",
      ],
      availabilityOppression: "Med",
      availabilitySecondary: { track: "H", requirement: "Low" },
    },
    player: {
      title: "Bitterwell Stand-Off",
      hook: "In the Bitterwell alleys, civilians are refusing to vacate their homes despite a shutter order. Guard enforcers will arrive soon. Your team must defuse the tension, negotiate time, and prevent bloodshed.",
    },
  },
  {
    gm: {
      id: "aetherbridge-dawnwalk",
      title: "Aetherbridge Dawnwalk",
      category: "Propaganda",
      hook: "Aetherbridge has panoramic overlooks that catch the city's dawnlight. Civilians want to take a 'dawnwalk' — a silent act of unity — despite Guard prohibition. Escort them discreetly and help them scatter before dawn light exposes them.",
      costR: 0,
      success: { H: 5, U: 5 },
      failure: { S: -5 },
      optionalInvestments: [
        {
          label: "Escort coordination",
          costR: 1,
          effectOnSuccess: { H: 5 },
        },
        {
          label: "Scatter routes",
          costR: 2,
          effectOnSuccess: { H: 5 },
          ruleText: "Ensure safe dispersal",
        },
      ],
      complications: [
        "Guard prohibition",
        "Dawn exposure",
        "Panoramic overlooks",
        "Aetherbridge",
      ],
      ties: ["Haven Cell", "Civilians", "Aetherbridge"],
      availabilityOppression: "Low",
      availabilitySecondary: { track: "H", requirement: "High" },
    },
    player: {
      title: "Aetherbridge Dawnwalk",
      hook: "Aetherbridge has panoramic overlooks that catch the city's dawnlight. Civilians want to take a 'dawnwalk' — a silent act of unity — despite Guard prohibition. Escort them discreetly and help them scatter before dawn light exposes them.",
    },
  },
];
